version: "3"
services:
  db:
    container_name: app_gar_db
    image: postgres
  web:
    container_name: app_ga_rails
    build: .
    command: bash -c "while [ true ]; do sleep 10; done"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db