version: "3"
services:
  db:
    container_name: app_gar_db
    image: postgres
  web:
    container_name: app_ga_rails
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db