default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: appgarails
  pool: 5

development:
  <<: *default
  database: app_ga_rails_development


test:
  <<: *default
  database: app_ga_rails_test

production:
  url: <%= ENV['DATABASE_URL'] %>